add_lunch_combo slim_galaxysmtd-userdebug
add_lunch_combo slim_grouper-userdebug
add_lunch_combo slim_hammerhead-userdebug
add_lunch_combo slim_i9100-userdebug
add_lunch_combo slim_i9300-userdebug
add_lunch_combo slim_jfltexx-userdebug
add_lunch_combo slim_maguro-userdebug
add_lunch_combo slim_mako-userdebug