add_lunch_combo slim_bacon-userdebug
add_lunch_combo slim_d802-userdebug
add_lunch_combo slim_grouper-userdebug
add_lunch_combo slim_hammerhead-userdebug
add_lunch_combo slim_i9100-userdebug
add_lunch_combo slim_i9300-userdebug
add_lunch_combo slim_jflte-userdebug
add_lunch_combo slim_mako-userdebug
add_lunch_combo slim_sirius-userdebug

